### ISSUE TITLE
Support of basic auth for git clone

### ISSUE THREAD

**Issue by nosovk** [mergestat/mergestat#1052]
We have some private repo, that hosted in some external env (gitea for example). There are a few ways to clone repo with authorization. SSH and HTTP with basic auth are most common ways.
We want to clone repo using HTTP/HTTPS with basic auth, for example:
https://user:pass@git.mysite.com/scm/repo.git
Expected result: pass authorization and clone repo inside mergestat.
Also, autoimport should support authorization in git URL.

**Comment by nosovk** [comment]
Is there any ETA on this feature?

**Comment by riyaz-ali** [comment]
@nosovk there isn't a native flow on the UI to support this yet. But you can create a new provider using the generic `git` option, and then add the credentials manually from either the queries pane or by using `psql` to connect to your postgres instance.

- To begin with, you'd need to create a new provider using the generic `git` option

![Add Gitea Provider](https://github.com/mergestat/mergestat/assets/17478576/17c86cc1-7141-4cbc-afd4-25da2dcb43f7)

- After creating the provider run the following query (substituting the appropriate values)

```postgresql
SELECT mergestat.add_service_auth_credential('<provider>', 'BASIC_AUTH', '<username>', '<credential>', '<secret>');
```

Here, `<secret>` is the value for the `ENCRYPTION_SECRET` environment variable.

**Comment by amenowanna** [comment]
@nosovk I am not sure how soon we will be able to prioritize the UI work for this but would love to learn if this workaround indeed works for you.

**Comment by nosovk** [comment]
Yep! Works great. I was able to add http basic auth and now can digging. I suggest adding above steps to documentation. Works like a charm :)

**Comment by amenowanna** [comment]
@nosovk So glad to hear this worked. We will definitely document this for now until we have a better solution in the UI.
