### ISSUE TITLE
Support docker-compose on Podman-based systems

### ISSUE THREAD

**Issue by mboes** [mergestat/mergestat#1071]
Internally, self-hosted Mergestat uses Podman. But the README says to call `docker-compose`. It would be good to support `podman-compose` up and down the stack. Currently, `podman-compose` does not work (containers fail to connect to the PostgreSQL db), and `docker-compose` on a Podman-based system does not work either. The error message in the latter case is:

```
$ docker-compose up
[...]
Error response from daemon: bad parameter: link is not supported
```

The reason for this error is the the `link` field in `docker-compose.yaml` is [legacy](https://docs.docker.com/network/links/) and Podman decided against implementing it in its Docker emulation.

It would be nice if Podman could be used top-to-bottom, including at the outermost level.

**Comment by amenowanna** [comment]
@mboes thank you for letting us know about this! Should be resolved now.
