### ISSUE TITLE
Update the descriptions of all sync types (in DB) for consistency 

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#111]
Probably should be done via a db migration. Basically, now that we pull that info into the UI, we should clean it up a bit and make it more descriptive.

~Dare I suggest we use markdown here, or is that too much?~

<img width="423" alt="image" src="https://user-images.githubusercontent.com/57259/182468771-db86ab29-52ec-48c7-988a-1c5d8f061af4.png">

- [ ] Add `short_name` column
- [ ] Update descriptions via migrations

**Comment by patrickdevivo** [comment]
Let's also add a "short name" column to the table for presenting the name in the UI

**Comment by patrickdevivo** [comment]
Sync Type | Description | Short Name
-- | -- | --
GIT_COMMITS | Retrieves the commit history of a repo | Git Commits
GIT_COMMIT_STATS | Retrieves commit stats for a repo | Git Commit Stats
GIT_FILES | Retrieves files (content and paths) of a git repo | Git Files
GITHUB_PR_COMMITS | Retrieves commits for all pull requests in a GitHub repo | GitHub PR Commits
GITHUB_PR_REVIEWS | Retrieves the reviews of all pull requests in a GitHub repo | GitHub PR Reviews
GITHUB_REPO_ISSUES | Retrieves all the issues of a GitHub repo | GitHub Repo Issues
GITHUB_REPO_METADATA | Retrieves metadata about a GitHub repo | GitHub Repo Metadata
GITHUB_REPO_PRS | Retrieves all the pull requests of a GitHub repo | GitHub Repo Pull Requests
GITHUB_REPO_STARS | Retrieves all stargazers of a GitHub repo | GitHub Repo Stars
GIT_REFS | Retrieves all the refs of a git repo | Git Refs

**Comment by amenowanna** [comment]
This achieves the goals of consistent wording and formatting. Approved!

**Comment by ramiroJCB** [comment]
@patrickdevivo  may I suggest change Short Name column to be short_name column ?

**Comment by patrickdevivo** [comment]
> @patrickdevivo may I suggest change Short Name column to be short_name column ?

@ramiroJCB  yep - `short_name` in the DB makes sense to me
