### ISSUE TITLE
Add retry logic when syncing data

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#148]
There are times when syncing data that we receive errors from GitHub that appear to be transient and we need to add retry logic so we can recover from this and not fail the whole sync.

Example error:
`Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include 'B08E:26B8:2DF08:7C8F1:62FFEEC1' when reporting this issue.`

Although we may not be able to address particular error because of the mergestat/mergestat dependency we can start by introducing retry logic on the dependencies we control like calls to the fuse database. Let's start by introducing retry logic to one of these integrations.

**Comment by patrickdevivo** [comment]
Closing this out as no longer relevant generally. Our new container-based sync approach will be able to make use of libraries such as `octokit` when working with the GitHub API, which has "out-of-the-box" support for retries/backoff.

Going forward, retry logic will generally be dependent on the implementation of the container-based sync, and we should opt for using the right SDKs for the job.
