### ISSUE TITLE
Consider some "top level" stats/metrics to display in `/repos` page?

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#222]
Above the main repos table, maybe some things like:

- Total number of repos (that match the current filters - tags and search terms)
- Avg. number of syncs per repo
- Avg. sync run time

etc. Basically some numbers (maybe small charts?) to give the user an aggregate sense of what their repo and sync data looks like

**Comment by emilyvandewalle** [comment]
Just wanted to quickly sketch this out in Figma first, would it be something like this?

![Image](https://user-images.githubusercontent.com/36261498/196748897-cea52d88-34f5-4672-a722-4ec6131a9c5b.png)

I also wanted to try a more visual version with colored boxes, but I'm wondering if it might become too cluttered as the repo table already contains a lot of visual elements. What do you think?

![Image](https://user-images.githubusercontent.com/36261498/196748763-73779a3a-66a8-4df7-bd01-6ffc4a89a25e.png)
