### ISSUE TITLE
Add support for `.mailmap` files

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#229]
See [here](https://git-scm.com/docs/gitmailmap) for context. It would be useful to be able use mappings in a `.mailmap` of a repo to de-duplicate authors in queries.

I'm not entirely sure how we add support for it - maybe as a helper function that takes the contents of a `.mailmap` and an email address, and returns the associated name.

Something like `SELECT mailmap(<mailmap-contents>, 'some@email.com')`

**Comment by chrisma** [comment]
It might also be an idea to represent the `mailmap` file as a DB table itself, that could be written and queried.
If a query is executed that is marked as using this mailmap table, contributors would be merged. That is how the git CLI does it. When a `.mailmap` file is found, all further commands respect it by default.

**Comment by patrickdevivo** [comment]
First version handled in this PR: https://github.com/mergestat/mergestat/pull/250

**Comment by chrisma** [comment]
I've added my idea of representing the contents of `.mailmap` as a table in MergeStat in a separate issue (#254) in case that's of interest
