### ISSUE TITLE
Is there a query to extract file content on a specific date?

### ISSUE THREAD

**Issue by aborruso** [mergestat/mergestat#248]
Hi to all,
imagine I have repo in which I update a txt file day by day.

Is there a way to have the version of this file on `2021-12-21`?

A query like `SELECT * FROM myFile.txt AS OF TIMESTAMP('2021-12-21');` that give me in output that file at that date?

Thank you

**Comment by aborruso** [comment]
@patrickdevivo wow, it seems really fantastic, thank you very much!!!!

Now I must study mergestat and install it. In debian, do I can install it, simply downloading the release files and extract them in the PATH?

**Comment by aborruso** [comment]
> the query is a bit verbose - maybe that's an interesting subcommand we could add, `mergestat file-as-of` or something like that, to show the contents of a file as of a certain date.

I think it would be really precious to have this command

**Comment by aborruso** [comment]
Hi @patrickdevivo, my input file is a csv. I have modified the query in this way:

```sql
mergestat --format csv "SELECT
  contents
FROM (
  SELECT * FROM commits
  WHERE author_when < date('2022-01-01')
  ORDER BY author_when DESC LIMIT 1
) AS c, files('', c.hash)
WHERE path LIKE 'input.csv'"
```

to have only the content.

Then I need to remove the first line of the output (I use `tail -n +2`), but I need to remove the `"` that I have at the start & at the end of my cell:

```
"fieldA,fieldB
a,1
b,7
q,3"
```

Then I have modified it in 

```sql
mergestat --format csv "SELECT
  contents
FROM (
  SELECT * FROM commits
  WHERE author_when < date('2022-01-01')
  ORDER BY author_when DESC LIMIT 1
) AS c, files('', c.hash)
WHERE path LIKE 'input.csv'" | tail -n +2 |tail -c +2 | head -c -2
```

It there a direct way to have only in output my CSV content, without `contents` heading and without heading and trailing double quotes?

```
fieldA,fieldB
a,1
b,7
q,3
```

mergestat seems to me fantastic, thank you

**Comment by patrickdevivo** [comment]
Hi @aborruso - that's an interesting use case! I can't think of an easy way as is to handle it as you say - maybe it's worth adding a `csv-noheader` output format option to exclude the headers.

As for the double quotes, I'm not sure - I think those are coming from the [csv writer](https://pkg.go.dev/encoding/csv) we're using, as it seems like it's csv "inside" csv.

Maybe it's worth bringing in a tool like [dasel](https://github.com/TomWright/dasel)? or possibly switch to `json` or `ndjson` output and use `jq` as well?

I can try to take a closer look as well and see if I can reproduce an example

**Comment by aborruso** [comment]
> or possibly switch to `json` or `ndjson` output and use `jq` as well?

In this way it's good for me. Thank you

```bash
mergestat --format json "SELECT
  contents
FROM (
  SELECT * FROM commits
  WHERE author_when < date('2021-01-01')
  ORDER BY author_when DESC LIMIT 1
) AS c, files('', c.hash)
WHERE path LIKE 'openregio_immobiliDestinati.csv'" | jq -r '.[0].contents'
```
