### ISSUE TITLE
Figure out how to convey `repo auto import` failures to the user

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#249]
Currently, if a repo auto import fails, nothing is conveyed to the user through the UI (because there's nothing in the DB/API to convey this). The only place it's reported is in the worker logs. This is not a great UX, especially because it's quite easy to trigger a failure state (if an org or username is mistyped for instance).

This ticket is for figuring out how to begin tracking repo import errors in the DB (emitted by the worker) so that we can eventually show it in the UI in some way.

**Comment by amenowanna** [comment]
Looping in the whole team on this one as we all will likely need to chip in. This ticket will need to be broken down. But from a starting point @ramiroJCB and I have just discussed the base problem which is the fact that we don't have a generic logging mechanism for the worker. So, what we are proposing is creating this generic logging mechanism that we can then use to create functions that the UI can call to determine if there are any errors for different functions including the auto imports. If y'all could please chime in with your thoughts on this then we can work on determining the path forward. @patrickdevivo of course we are looking for your opinion.

**Comment by patrickdevivo** [comment]
My suggestion would be to solve the specific problem for repo auto imports first, and treat the more generic solution as a separate problem. I know this feels backwards, but I think the generic problem we'll want to tackle goes beyond logging and is more about how we handle async work in general - and will be a bigger uplift. We have a handful of async patterns already in place, all done slightly differently:

- Repo data syncs (the most obvious) - backend worker picks up jobs from a queue, does work, logs to DB
- Repo auto imports - the worker, on an interval, imports new repos from the GitHub API. No logs sent to DB (or very much status info either)
- Scheduler and timeout process - runs in the worker on a timer (like a cronjob) and takes actions in the DB, only log output is to stdout/stderr
- **future:** data syncs not tied to repos (tied to orgs/accounts such as JIRA or PagerDuty etc)
- **future:** query executions from the UI (to support long running queries that dont belong in an HTTP request and storing their results)
- **future:** scheduling and alerting behavior - allow a user to run a query on a schedule/interval and send the results somewhere (slack, email, etc)

So my take on this would be let's solve the repo auto imports first, enough to get the user experience problem addressed (where if a user has a bad token or there's an error in an auto import, nothing is reported), because I think we can resolve that quicker than a refactor to async patterns in general. Then let's use learnings there and across our other async work to make a plan for a _generic_ async pattern that can support all our current and future use cases, and implement that, and begin migrating to it.

How does that sound?

For the "quick" solution to repo auto imports, my suggestion would be:

- Additional columns in the repo auto imports table to hold status information of the last run (success/failure, any associated messages, maybe a count of new repos added)
- Update the repo auto import routine to populate those columns
- Update the UI to make use of those columns 

The "foundation" work we need to do for async work generally could/should have:

- distributed queue implementation to hold async work (priority? multiple queues? job statuses?) do we implement our own in PG or bring in another solution?
- log pattern in DB for holding log output of async work
- etc...

**Comment by amenowanna** [comment]
I think you are coupling the async work too much to the logging. That being said I am good with the proposed solution to just add some columns to the imports table to track errors. That is simple and we can knock that out quickly. Since it is in the table we shouldn't even need a function the basic graphql calls should be sufficient.
