### ISSUE TITLE
Nesting in mergestat/sqlite?

### ISSUE THREAD

**Issue by robmoffat** [mergestat/mergestat#290]
Hi,

Please forgive the "noob" question but I couldn't find this in my searching.  If I wanted to do a SELECT over all the issues in all the repos in an organisation, how would I go about this?

It seems like the virtual table parameters are going to hard-code to a particular repo. Is this right?

thanks,
Rob

**Comment by patrickdevivo** [comment]
No problem! Not a "noob" question at all 😃 . Here's the quick answer:

```sql
SELECT * FROM github_org_repos('mergestat') repo, github_issues('mergestat', repo.name)
```

That should iterate over all repos belonging to an org, and then for each repo fetch all issues, assuming you have the `GITHUB_TOKEN` env var set. If you supply the `-v` flag when running, you can see the API requests being made as well. Presumably you may want `-f json` or `-f csv` to format the output as well.

Let me know if that helps! Feel free to ask in our [community slack](https://join.slack.com/t/mergestatcommunity/shared_invite/zt-xvvtvcz9-w3JJVIdhLgEWrVrKKNXOYg) if that's any easier

**Comment by robmoffat** [comment]
works, thanks!
