### ISSUE TITLE
Bug when browsing back from Managing Repo Imports

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#328]
When browsing backwards from the `Manage Repo Auto Imports` section I am not returned to the previous page in the UI. When  we first noticed this yesterday while testing it sent us back to the `Connections` page but today I am getting the behavior shared below.

![Image](https://user-images.githubusercontent.com/10135546/192816276-f496be70-235e-48ee-ae5c-67464fbc1fa6.gif)

**Comment by patrickdevivo** [comment]
Closing out as no longer relevant
