### ISSUE TITLE
Investigate alternatives for handling migrations

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#331]
We've had a fair amount of pain with our current solution, especially when it comes to needing manual intervention on failures.

Let's investigate alternatives that fit our needs better.

**Comment by amenowanna** [comment]
I started this work last weekend and narrowed the playing field to Atlas which was brought up in an issue by our community but also the migrations that are supported by sqlc:

[atlas](https://atlasgo.io/)

[dbmate](https://github.com/amacneil/dbmate)

[golang-migrate](https://github.com/golang-migrate/migrate)

[goose](https://github.com/pressly/goose)

[sql-migrate](https://github.com/rubenv/sql-migrate)

[tern](https://github.com/jackc/tern)

Features that I am looking for:
1. Migrations that can be run from command line as well as from code
2. Migration history table that gives a full history of migrations
3. Sequential migrations so we do not have the same issues we have today with date driven migration order
4. Recovery paths that do nor require manual intervention
5. Does not enforce down migrations but simply attempt to run migrations again. This would allow us to mend a broken migration and deploy it again without having to manually intervene like we do today with golang-migrate
6. Allows for concurrent index creation
I have ruled out Atlas as it requires its own ddl and this is a personal preference from bad experiences with similar solutions to not choose this over native declaration.

**Comment by patrickdevivo** [comment]
I'd also like to add this to the list: https://github.com/graphile/migrate since we're already using graphile at the GraphQL API layer, it might be worth investigating their approach to migrations as well

**Comment by amenowanna** [comment]
Good candidate! Interesting to see the compliment comes from something postgraphile doesn't really encourage for prod.  

> complements [PostGraphile](https://graphile.org/postgraphile/) — works with any application, but PostGraphile's watch mode means that the GraphQL schema is instantly regenerated (without server restart) whenever the database changes

**Comment by amenowanna** [comment]
We have a very good alternative the has been added to sqlq and I am proposing we continue to use the solution we have now until we have an internal tool we can consume.
