### ISSUE TITLE
Log out dropdown is hidden by alert

### ISSUE THREAD

**Issue by emilyvandewalle** [mergestat/mergestat#415]
- The distance between the toggle and log out dropdown is a bit too much 
- The dropdown is hidden when there are alert messages

![Image](https://user-images.githubusercontent.com/36261498/196941255-af849e63-7c05-426c-b651-b59888f4e9cd.png)

![Image](https://user-images.githubusercontent.com/36261498/196941478-59c1be8c-4eb9-41e9-8293-d2a505761a37.png)

**Comment by patrickdevivo** [comment]
Closing as we've addressed by moving the notifications to the bottom right
