### ISSUE TITLE
Query results should show a different message when no results are returned

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#422]
When running a query that returns no results the results/table section shows the same message which makes the experience feel like something didn't execute. We should show a different message. `Empty result set (no rows returned)`

![Image](https://user-images.githubusercontent.com/10135546/197208339-1295520b-fb7d-42a3-911e-ef44f28b9fb2.png)

**Comment by amenowanna** [comment]
@patrickdevivo would like your input on what message to display.

**Comment by patrickdevivo** [comment]
How about

```
Empty result set (no rows returned)
```

And maybe we can use the `-` icon we use elsewhere to indicate `0`/`null`?

**Comment by amenowanna** [comment]
Updated the description to use the verbiage we want to have.
