### ISSUE TITLE
Error in `GIT_BLAME` sync

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#439]
```
{
insertId: "ydsw7ftb99macmup"
jsonPayload: {
error: "bufio.Scanner: token too long"
level: "error"
message: "error blaming file in repo: /tmp/mergestat-repo-2765930869, bufio.Scanner: token too long"
}
labels: {5}
logName: "projects/mergestat-internal/logs/stderr"
receiveTimestamp: "2022-10-26T16:56:58.414527902Z"
resource: {2}
severity: "ERROR"
timestamp: "2022-10-26T16:56:57Z"
}
```

Sometimes we encounter this, probably need to tune the `Scanner` to accept longer tokens (within reason)

**Comment by ramiroJCB** [comment]
@patrickdevivo  didn't your last PR solve this issue ?  or do we have a way to replicate this and test

**Comment by patrickdevivo** [comment]
Yep! Latest PR should address this. There still may be lines that are too long that trigger this, but this will also be handled as a warning vs an error. So I will close this out.
