### ISSUE TITLE
spinner keeps spinning  after errors from the importer

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#440]
here is picture after a typo error from the importer 

![Image](https://user-images.githubusercontent.com/43893061/198092646-25104948-54f7-47c9-8b66-63b02a994883.png)

**Comment by amenowanna** [comment]
relates to #249

**Comment by patrickdevivo** [comment]
I am going to close this out in favor of this issue: https://github.com/mergestat/mergestat/issues/559 as they cover the same ground
