### ISSUE TITLE
Add Warning messages to database logs

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#456]
As part of our logging improvements we are now tracking Warning level log messages. We need to add these Warning messages to the database logs so we can bubble them up to the UI in both the logs sections as well as in the /repos experience like we do with Errors.

**Comment by patrickdevivo** [comment]
This would likely involve adding a row to the `mergestat.repo_sync_log_types` table via a migration, and possibly updating any helpers in the worker (I think there's one for doing a bulk insert of sync logs) to support the new message type.

Might be worth considering some places in existing syncs where a `WARNING` could be useful as well.
