### ISSUE TITLE
Add filter "Created" to the workflow runs request in the Actions Sync

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#460]
We need way  to control from when we  are starting to fetch data from runs  and proceduraly  from jobs  and logs.
Not only this helps out  to  not drowing out other syncs from the amount data collected  but also will help with the  data retention  policy that github have with Logs of any kind . 

- Here is the link  that proves that is possible https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository .
- here is a link that shows the retention policy for logs https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization

The way of testing this is to check if have any records older from the starting point  :)

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
