### ISSUE TITLE
We need to change warehouse starting pattern

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#461]
right now we are starting a new warehouse operation by  calling 
`warehouse.new(params).githubactions(params)`
It will be a better pattern to do  :
`warehouse.new(params).start(ctx,job)` 
or something similar , that way we  handle the  job inside the start or whatever fn it be with a switch case statement   and generate whatever dependencies are need  for that specific job.
Its a more organize and concise  pattern .

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
