### ISSUE TITLE
Syncs that fail consistently are not "surfaced" very well

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#480]
If there's a repo sync that's always failing, but also frequently re-queued, it will more often appear as "Queued" in the `/repos` page (and not `Error` - even tho it's consistently erroring). This makes sense given how we currently implement the status experience, however it's not a great UX because this is a sync that we _want_ to bubble to the user as erroring frequently.

Can we consider an experience for surfacing these types of consistently failing syncs to the user more clearly? Maybe some kind of alert or banner that appears if a sync has failed consistently over N times?

<img width="870" alt="image" src="https://user-images.githubusercontent.com/57259/199071986-8e9338ff-af26-4625-85a5-4582df02c63c.png">

**Comment by amenowanna** [comment]
Addressed in the latest updates to the /repos experience as we show errors on the last run of a sync.
