### ISSUE TITLE
`/repos` page timing out on deployments with many repos (and big sync history)

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#483]
We received a report from a user with 800+ repos imported and many active syncs that the console times out when loading `/repos`. My _guess_ without knowing much more is that our query to display the `Total syncs with errors` number is taking a long time to run (or at least that's the first place I'd look).

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/57259/199076545-d8320cc2-4663-4141-969e-bff97249aae7.png">

We might need to optimize somewhere to ensure whatever query is causing the timeout/slow response is speedy.

**Comment by amenowanna** [comment]
Working on optimizing the `Total syncs with errors` as this is the bottleneck we are seeing in our internal deployment.
