### ISSUE TITLE
Add support for SSH git repositories

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#507]
We should be able to support SSH git repositories in addition to HTTPs repos. In addition, we should make it possible/easy for a user to supply an SSH key to use when cloning/retrieving SSH repos.

**Comment by halcyondude** [comment]
Also needed for GitHub Enterprise

**Comment by riyaz-ali** [comment]
This is possible now! (though not directly via the UI) refer to #1052 for more details
