### ISSUE TITLE
Implement the UI for user management

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#530]
Now that we have mockups (https://github.com/mergestat/internal/issues/87) and the backend implementation is almost complete (https://github.com/mergestat/mergestat/issues/505) we should begin implementing in the UI

**Comment by amenowanna** [comment]
@german-mergestat here are the example function calls in the DB so you can see what params the calls need. https://github.com/mergestat/mergestat/blob/main/scripts/validate-users.sql
