### ISSUE TITLE
Consider making the repo auto imports use the v3 GitHub REST API

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#540]
This would potentially allow us to support GitHub repo auto imports _without_ a token (need to validate this). It would only work for public repos, but it could enable an interesting onboarding path for someone trying out MergeStat without needing to setup a token (and still see data for a lot of repos)

**Comment by ramiroJCB** [comment]
We managed to make  the feature with Rest API approach . The only  downside  is that this Syncs wont work withour proper validation 
1. PR Commits
2. Pr Reviews
3. Repo Issues
4. Repo metadata
5. Pull Requests
6. Repo Stars
