### ISSUE TITLE
mergestat_role_admin was not granted all privs to public schema

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#548]
When adding repos as a user with the `ADMIN` role I received permissions issues. Looking at the PR that added this role I found that only the `SELECT` priv was granted to the public schema. We need to make sure that the 'ADMIN' role has all priveleges granted.

**Comment by patrickdevivo** [comment]
good catch - https://github.com/mergestat/mergestat/pull/512/files#diff-0dfaaed28809f28866c76f0dc47329d256504e6ace701ca87596c053fdc6b7a9R48
