### ISSUE TITLE
Revaluate handling of repo sync jobs when worker is shutdown

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#580]
We should evaluate how we handle shutting down the worker gracefully.

Currently, when the worker is shutdown, a [context cancellation](https://github.com/mergestat/mergestat/blob/main/cmd/worker/main.go#L232) is passed through to all running repo sync jobs. The worker is _supposed_ to [mark any inflight jobs](https://github.com/mergestat/mergestat/blob/main/internal/syncer/syncer.go#L131) as `QUEUED` (re-queue) them to get picked up later by a new worker. Often this doesn't happen, I'm guessing because of a timing issue or maybe a problem with our logic.

We should look at this holistically and figure out what we want the behavior to be, and implement a fix accordingly.

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
