### ISSUE TITLE
Unable to initialize the  trivy scan when repository is not found

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#582]
When somehow the repository is not found , the trivy scanner fails .
Logs:
`{
  "insertId": "9mfbp3ttxoi4gwky",
  "jsonPayload": {
    "error": "exit status 1",
    "level": "error",
    "stderr": "2022-11-28T18:40:27.218Z\t\u001b[31mFATAL\u001b[0m\trepository scan error: scan error: unable to initialize a scanner: unable to initialize a filesystem scanner: git clone error: repository not found\n",
    "message": "error running trivy scan"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "location": "us-central1",
      "container_name": "mergestat-worker",
      "pod_name": "mergestat-worker-7b74db6dd8-jbt6h",
      "namespace_name": "default",
      "project_id": "oss-dashboards",
      "cluster_name": "oss-dashboards-gke"
    }
  },
  "timestamp": "2022-11-28T18:40:27Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/app_kubernetes_io/instance": "mergestat",
    "k8s-pod/app_kubernetes_io/name": "mergestat",
    "compute.googleapis.com/resource_name": "gk3-oss-dashboards-gke-nap-19h7tyta-b1d506ed-67pw",
    "k8s-pod/pod-template-hash": "7b74db6dd8",
    "k8s-pod/mergestat-component": "worker"
  },
  "logName": "projects/oss-dashboards/logs/stderr",
  "receiveTimestamp": "2022-11-28T18:40:28.504640268Z"
}`

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
