### ISSUE TITLE
Nil pointer running syft repo scan

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#583]
We found nil pointer deference running syft repo scan
Logs:`{
  "insertId": "niq4dfdkervpt3ci",
  "jsonPayload": {
    "level": "error",
    "message": "error running syft repo scan",
    "error": "exit status 2",
    "stderr": "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x19d94e8]\n\ngoroutine 72 [running]:\ndebug/macho.NewFile({0x7fa089d37c58?, 0xc007df79c8})\n\t/Users/runner/hostedtoolcache/go/1.18.6/x64/src/debug/macho/file.go:348 +0x5a8\ndebug/buildinfo.readRawBuildInfo({0x7fa089d37c58, 0xc007df79c8})\n\t/Users/runner/hostedtoolcache/go/1.18.6/x64/src/debug/buildinfo/buildinfo.go:122 +0x287\ndebug/buildinfo.Read({0x7fa089d37c58?, 0xc007df79c8?})\n\t/Users/runner/hostedtoolcache/go/1.18.6/x64/src/debug/buildinfo/buildinfo.go:74 +0x27\ngithub.com/anchore/syft/syft/pkg/cataloger/golang.scanFile({0x7fa089d37c20?, 0xc007df79c8?}, {0xc007a4af7f, 0x37})\n\t/Users/runner/work/syft/syft/syft/pkg/cataloger/golang/scan_bin.go:23 +0x1b0\ngithub.com/anchore/syft/syft/pkg/cataloger/golang.(*Cataloger).Catalog(0x24dec92?, {0x28c30d8, 0xc00025e0e0})\n\t/Users/runner/work/syft/syft/syft/pkg/cataloger/golang/binary_cataloger.go:52 +0x405\ngithub.com/anchore/syft/syft/pkg/cataloger.Catalog({0x28c30d8?, 0xc00025e0e0}, 0x8?, {0xc000574160, 0x15, 0x0?})\n\t/Users/runner/work/syft/syft/syft/pkg/cataloger/catalog.go:56 +0x3d8\ngithub.com/anchore/syft/syft.CatalogPackages(0xc000180160, {{0x1, 0x0, {0x24a5a7b, 0x8}}, {0x0, 0x0, 0x0}})\n\t/Users/runner/work/syft/syft/syft/lib.go:72 +0x56f\ngithub.com/anchore/syft/cmd/syft/cli/eventloop.generateCatalogPackagesTask.func1(0xc000682340, 0xc000180160?)\n\t/Users/runner/work/syft/syft/cmd/syft/cli/eventloop/tasks.go:49 +0xe5\ngithub.com/anchore/syft/cmd/syft/cli/eventloop.RunTask(0x0?, 0x0?, 0x53b616?, 0xc0005ce2a0, 0x1c?)\n\t/Users/runner/work/syft/syft/cmd/syft/cli/eventloop/tasks.go:223 +0x85\ncreated by github.com/anchore/syft/cmd/syft/cli/packages.buildRelationships\n\t/Users/runner/work/syft/syft/cmd/syft/cli/packages/packages.go:131 +0x65\n"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "pod_name": "mergestat-worker-7b74db6dd8-xlhtg",
      "cluster_name": "oss-dashboards-gke",
      "location": "us-central1",
      "container_name": "mergestat-worker",
      "namespace_name": "default",
      "project_id": "oss-dashboards"
    }
  },
  "timestamp": "2022-11-28T05:06:26Z",
  "severity": "ERROR",
  "labels": {
    "compute.googleapis.com/resource_name": "gk3-oss-dashboards-gke-nap-19h7tyta-b1d506ed-67pw",
    "k8s-pod/app_kubernetes_io/instance": "mergestat",
    "k8s-pod/mergestat-component": "worker",
    "k8s-pod/app_kubernetes_io/name": "mergestat",
    "k8s-pod/pod-template-hash": "7b74db6dd8"
  },
  "logName": "projects/oss-dashboards/logs/stderr",
  "receiveTimestamp": "2022-11-28T05:06:28.500794587Z"
}`

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
