### ISSUE TITLE
Error reading temporary directories

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#584]
Seem that we fail regularly to read our temporary directories  when we create them 
Logs:`{
  "insertId": "i817n4z1difm23lj",
  "jsonPayload": {
    "message": "error reading file in repo: /tmp/mergestat-repo-4262377642/archive/test-fixtures/archive-symlink/link/link, read /tmp/mergestat-repo-4262377642/archive/test-fixtures/archive-symlink/link/link: is a directory",
    "error": "read /tmp/mergestat-repo-4262377642/archive/test-fixtures/archive-symlink/link/link: is a directory",
    "level": "error"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "namespace_name": "default",
      "location": "us-central1",
      "pod_name": "mergestat-worker-ccc6c4dd8-59xvg",
      "project_id": "oss-dashboards",
      "cluster_name": "oss-dashboards-gke",
      "container_name": "mergestat-worker"
    }
  },
  "timestamp": "2022-11-27T12:50:15Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/app_kubernetes_io/name": "mergestat",
    "k8s-pod/mergestat-component": "worker",
    "k8s-pod/pod-template-hash": "ccc6c4dd8",
    "compute.googleapis.com/resource_name": "gk3-oss-dashboards-gke-nap-19h7tyta-55bd78c4-nlxl",
    "k8s-pod/app_kubernetes_io/instance": "mergestat"
  },
  "logName": "projects/oss-dashboards/logs/stderr",
  "receiveTimestamp": "2022-11-27T12:50:20.024121847Z"
}`

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
