### ISSUE TITLE
Implement first pass of very basic data visualization in `Queries` area

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#585]
See the comments in this issue: https://github.com/mergestat/internal/issues/86 we've done a Figma pass at basic data visualizations in the `Queries` section.

This ticket is to track the UI work for the _first pass_ at implementing **basic** data viz. In fact, for this ticket let's **only** focus on:

- The overall structure changes we need to make to the query results area (to support the tabs for new "views"
- The single metric "visualization" type

![Image](https://user-images.githubusercontent.com/57259/204394591-b14b4c9d-0200-4e96-98a1-068d40406dab.png)

We will tackle the charts and other options in subsequent tickets.

**Comment by amenowanna** [comment]
@patrickdevivo @emilyvandewalle Is the "Number" drop down in this design meant to be a reference to a column name or to a  number format? I think this should be for formatting but I could also imagine a query that returns a row with several metrics but we only display the one so we would need to reference a column. That being said I think for a first pass the single metric viz should expect a query that only returns one row with one metric and that we do not do column selection. Thoughts?

**Comment by amenowanna** [comment]
This is going to be very basic. This would be something I think we need to have live on a branch or if we had feature flags I would suggest we use them there. Apex does not have a single metric component so this one is going to have to be homegrown. I would also suggest we don't implement download on this for now as it seems like early optimization on this homegrown component but I won't fight anyone on that.

**Comment by amenowanna** [comment]
@german-mergestat here are some decisions that @patrickdevivo and I made about this feature.

1. The number drop down should list the available columns from the query to use for the metric
2. The download and save to dashboards are not needed for now
3. We should go ahead and add the Line and Bar chart options but grey them out until we implement them
4. The number that we show in the metric will be the first number returned in the column that is selected. So on this example only `1` or `2` could be shown based on what column is selected 


![Image](https://user-images.githubusercontent.com/10135546/212392870-a2adaf3f-0b04-4c00-90de-a554136af293.png)
