### ISSUE TITLE
Error getting query files in git_files

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#586]
To get git files we use our mergestat-lite dep , when we use `w.mergestat.SelectContext`  we fail   getting some refs.
Logs:`{
  "insertId": "gxlhebofdmz12110",
  "jsonPayload": {
    "error": "mergestat query files: reference 'refs/heads/master' not found",
    "message": "error handling job: &{394245 2022-11-28 15:43:49.505429 +0000 UTC RUNNING 5b013e23-8b84-4b0d-b367-49a2a5b0e7c3 13685e8e-76ba-4bf5-ab4e-1fd1debe9da2 GIT_FILES {[123 125] 2} 5b013e23-8b84-4b0d-b367-49a2a5b0e7c3 false 0 {0 false} https://bitbucket.org/VladislavPesetskiy/test_for_test_and_test/src { false} {false true} {[123 125] 2}}",
    "level": "error"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "pod_name": "mergestat-worker-7b74db6dd8-mdc59",
      "namespace_name": "default",
      "cluster_name": "oss-dashboards-gke",
      "project_id": "oss-dashboards",
      "location": "us-central1",
      "container_name": "mergestat-worker"
    }
  },
  "timestamp": "2022-11-28T15:44:03Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/app_kubernetes_io/name": "mergestat",
    "k8s-pod/mergestat-component": "worker",
    "compute.googleapis.com/resource_name": "gk3-oss-dashboards-gke-nap-19h7tyta-b1d506ed-67pw",
    "k8s-pod/app_kubernetes_io/instance": "mergestat",
    "k8s-pod/pod-template-hash": "7b74db6dd8"
  },
  "logName": "projects/oss-dashboards/logs/stderr",
  "receiveTimestamp": "2022-11-28T15:44:08.497109111Z"
}`

**Comment by ramiroJCB** [comment]
This error will be turned into warn error with the new changes , so the filter will be removed from Terraform

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
