### ISSUE TITLE
Invalid byte sequence in git_commit sync

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#587]
I don't know in which part of the code this is happening but seems to happen often , that our git commit sync we read and invalid byte sequence and failing the job
Logs:`{
  "insertId": "nfn7wgqa9d3ouw7k",
  "jsonPayload": {
    "message": "error handling job: &{390305 2022-11-28 12:39:00.289855 +0000 UTC RUNNING de2f597c-2904-417d-9cc1-049e8e72a4d5 932ff0d9-4337-4f63-bd25-6155fc222632 GIT_COMMITS {[123 125] 2} de2f597c-2904-417d-9cc1-049e8e72a4d5 true 2 {378964 true} https://github.com/clickhouse/cyrus-sasl { false} {true true} {[123 125] 2}}",
    "error": "ERROR: invalid byte sequence for encoding \"UTF8\": 0xe8 0x72 0x65 (SQLSTATE 22021)",
    "level": "error"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "cluster_name": "oss-dashboards-gke",
      "project_id": "oss-dashboards",
      "pod_name": "mergestat-worker-7b74db6dd8-jbt6h",
      "namespace_name": "default",
      "container_name": "mergestat-worker",
      "location": "us-central1"
    }
  },
  "timestamp": "2022-11-28T18:24:20Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/app_kubernetes_io/instance": "mergestat",
    "k8s-pod/pod-template-hash": "7b74db6dd8",
    "k8s-pod/app_kubernetes_io/name": "mergestat",
    "k8s-pod/mergestat-component": "worker",
    "compute.googleapis.com/resource_name": "gk3-oss-dashboards-gke-nap-19h7tyta-b1d506ed-67pw"
  },
  "logName": "projects/oss-dashboards/logs/stderr",
  "receiveTimestamp": "2022-11-28T18:24:23.501165449Z"
}`

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
