### ISSUE TITLE
Error opening our tmp directories

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#588]
Similar to https://github.com/mergestat/mergestat/issues/584 , this one when we  try to open a newly created  tmp dir  it fails  because it does not exits.
Logs:`{
  "insertId": "wcpaodntk80p7a7i",
  "jsonPayload": {
    "message": "error opening file in repo: /tmp/mergestat-repo-1004314037/.eslintrc.json, open /tmp/mergestat-repo-1004314037/.eslintrc.json: no such file or directory",
    "level": "error",
    "error": "open /tmp/mergestat-repo-1004314037/.eslintrc.json: no such file or directory"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "location": "us-central1",
      "container_name": "mergestat-worker",
      "namespace_name": "default",
      "cluster_name": "oss-dashboards-gke",
      "pod_name": "mergestat-worker-ccc6c4dd8-xtqrq",
      "project_id": "oss-dashboards"
    }
  },
  "timestamp": "2022-11-27T11:43:44Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/pod-template-hash": "ccc6c4dd8",
    "k8s-pod/mergestat-component": "worker",
    "k8s-pod/app_kubernetes_io/instance": "mergestat",
    "compute.googleapis.com/resource_name": "gk3-oss-dashboards-gke-nap-19h7tyta-55bd78c4-nlxl",
    "k8s-pod/app_kubernetes_io/name": "mergestat"
  },
  "logName": "projects/oss-dashboards/logs/stderr",
  "receiveTimestamp": "2022-11-27T11:43:45.033002244Z"
}`

**Comment by amenowanna** [comment]
Closing as we are using container syncs now
