### ISSUE TITLE
Seem like our bufio scanner at git_blame is too short

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#589]
Many times  our bufio scanner fails because  of a too long token .
Logs:`{
  "insertId": "zdxbwwwr423m5sro",
  "jsonPayload": {
    "error": "bufio.Scanner: token too long",
    "message": "error blaming file: docs/fa/changelog/index.html in repo: /tmp/mergestat-repo-3241647251, bufio.Scanner: token too long",
    "level": "error"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "pod_name": "mergestat-worker-ccc6c4dd8-59xvg",
      "container_name": "mergestat-worker",
      "project_id": "oss-dashboards",
      "cluster_name": "oss-dashboards-gke",
      "location": "us-central1",
      "namespace_name": "default"
    }
  },
  "timestamp": "2022-11-27T13:08:34Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/app_kubernetes_io/name": "mergestat",
    "compute.googleapis.com/resource_name": "gk3-oss-dashboards-gke-nap-19h7tyta-55bd78c4-nlxl",
    "k8s-pod/pod-template-hash": "ccc6c4dd8",
    "k8s-pod/mergestat-component": "worker",
    "k8s-pod/app_kubernetes_io/instance": "mergestat"
  },
  "logName": "projects/oss-dashboards/logs/stderr",
  "receiveTimestamp": "2022-11-27T13:08:35.027898073Z"
}`

**Comment by amenowanna** [comment]
closing as we are using container syncs now
