### ISSUE TITLE
Error opening tmp dir when it have to mane levels of symbolic links

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#594]
Seems like in our git_blame sync , we encounter the error of opening a tmp directory with to many symbolic links
Logs:`{
  "insertId": "bj38st22mcm8sp9m",
  "jsonPayload": {
    "message": "error opening file in repo: /tmp/mergestat-repo-2237029105/deploy/iso/minikube-iso/board/minikube/x86_64/rootfs-overlay/etc/udev/rules.d/80-net-setup-link.rules, open /tmp/mergestat-repo-2237029105/deploy/iso/minikube-iso/board/minikube/x86_64/rootfs-overlay/etc/udev/rules.d/80-net-setup-link.rules: too many levels of symbolic links",
    "level": "error",
    "error": "open /tmp/mergestat-repo-2237029105/deploy/iso/minikube-iso/board/minikube/x86_64/rootfs-overlay/etc/udev/rules.d/80-net-setup-link.rules: too many levels of symbolic links"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "namespace_name": "default",
      "cluster_name": "oss-dashboards-gke",
      "location": "us-central1",
      "pod_name": "mergestat-worker-ccc6c4dd8-cl7c7",
      "container_name": "mergestat-worker",
      "project_id": "oss-dashboards"
    }
  },
  "timestamp": "2022-11-26T11:21:59Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/pod-template-hash": "ccc6c4dd8",
    "k8s-pod/app_kubernetes_io/instance": "mergestat",
    "k8s-pod/mergestat-component": "worker",
    "k8s-pod/app_kubernetes_io/name": "mergestat",
    "compute.googleapis.com/resource_name": "gk3-oss-dashboards-gke-nap-19h7tyta-55bd78c4-nlxl"
  },
  "logName": "projects/oss-dashboards/logs/stderr",
  "receiveTimestamp": "2022-11-26T11:22:00.035892312Z"
}`

**Comment by amenowanna** [comment]
closing as we are using container syncs now
