### ISSUE TITLE
Possible error comming  from gitutils usage in git_blame sync

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#600]
we found a panic error running blame sync , the trace. indicates that is probable from gitutils
Logs:`{
  "textPayload": "panic: runtime error: index out of range [1] with length 1\n\ngoroutine 73 [running]:\ngithub.com/mergestat/gitutils/blame.parseLinePorcelain({0x179a220?, 0xc192b0a6d0?}, 0xc0024ed8b8?)\n\t/go/pkg/mod/github.com/mergestat/gitutils@v0.0.0-20221108145951-dde3591e4b3b/blame/blame.go:144 +0x123f\ngithub.com/mergestat/gitutils/blame.Exec({0x17a2670?, 0xc0001c5e00}, {0xc001e0ab60, 0x1e}, {0xc016023b35, 0x26}, {0xc0024efae0, 0x1, 0x1?})\n\t/go/pkg/mod/github.com/mergestat/gitutils@v0.0.0-20221108145951-dde3591e4b3b/blame/blame.go:224 +0x337\ngithub.com/mergestat/mergestat/internal/syncer.(*worker).handleGitBlame(0xc001090c60, {0x17a2670, 0xc0001c5e00}, 0xc00007e000)\n\t/src/internal/syncer/git_blame.go:161 +0xd49\ngithub.com/mergestat/mergestat/internal/syncer.(*worker).handle(0xc000125080?, {0x17a2670, 0xc0001c5e00}, 0xc00007e000)\n\t/src/internal/syncer/syncer.go:161 +0x152\ngithub.com/mergestat/mergestat/internal/syncer.(*worker).exec(0xc001090c60, {0x17a2670, 0xc0001c5e00}, {0x2357a68, 0x1})\n\t/src/internal/syncer/syncer.go:111 +0x22c\ngithub.com/mergestat/mergestat/internal/syncer.(*worker).Start.func1(0x0?)\n\t/src/internal/syncer/syncer.go:191 +0x90\ncreated by github.com/mergestat/mergestat/internal/syncer.(*worker).Start\n\t/src/internal/syncer/syncer.go:190 +0x5d",
  "insertId": "la22bx3ojh85auw5",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "pod_name": "mergestat-worker-686c59f974-gg94m",
      "location": "us-central1",
      "container_name": "mergestat-worker",
      "namespace_name": "default",
      "cluster_name": "beta-deployment-acme-inc-gke",
      "project_id": "beta-deployment-acme-inc"
    }
  },
  "timestamp": "2022-11-30T10:07:59.049103250Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/mergestat-component": "worker",
    "k8s-pod/pod-template-hash": "686c59f974",
    "compute.googleapis.com/resource_name": "gk3-beta-deployment-acme-nap-g7q70sba-9d33feeb-z5kk",
    "k8s-pod/app_kubernetes_io/instance": "mergestat",
    "k8s-pod/app_kubernetes_io/name": "mergestat"
  },
  "logName": "projects/beta-deployment-acme-inc/logs/stderr",
  "receiveTimestamp": "2022-11-30T10:08:18.489023478Z"
}`

**Comment by amenowanna** [comment]
closing as we are using container syncs now
