### ISSUE TITLE
repo sync logs violates foreign key constraint

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/mergestat#601]
seems like we have had some foreign key constraint 
Logs:`
{
  "insertId": "gesva5e7psdswulp",
  "jsonPayload": {
    "level": "error",
    "message": "error sending log error message: ERROR: insert or update on table \"repo_sync_logs\" violates foreign key constraint \"repo_sync_logs_repo_sync_queue_id_fkey\" (SQLSTATE 23503)",
    "error": "ERROR: insert or update on table \"repo_sync_logs\" violates foreign key constraint \"repo_sync_logs_repo_sync_queue_id_fkey\" (SQLSTATE 23503)"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "cluster_name": "beta-deployment-acme-inc-gke",
      "location": "us-central1",
      "pod_name": "mergestat-worker-66d9c4d786-fjc48",
      "namespace_name": "default",
      "container_name": "mergestat-worker",
      "project_id": "beta-deployment-acme-inc"
    }
  },
  "timestamp": "2022-11-29T02:56:12Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/pod-template-hash": "66d9c4d786",
    "k8s-pod/mergestat-component": "worker",
    "compute.googleapis.com/resource_name": "gk3-beta-deployment-acme-nap-g7q70sba-9d33feeb-z5kk",
    "k8s-pod/app_kubernetes_io/name": "mergestat",
    "k8s-pod/app_kubernetes_io/instance": "mergestat"
  },
  "logName": "projects/beta-deployment-acme-inc/logs/stderr",
  "receiveTimestamp": "2022-11-29T02:56:13.005966722Z"
}
`

**Comment by amenowanna** [comment]
This was related to the broken migration #629
