### ISSUE TITLE
Use a longer timeout when running migrations

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#611]
It seems like the default timeout in the migration tool we use is 15 seconds: https://github.com/golang-migrate/migrate/blob/31791adbc0e4f45e0cb13fbc3d13095b78709dc6/migrate.go#L29

This not be long enough for certain "big deployments" where schema changes may take more time to execute. As a "quick fix" see if we can override the default (and/or expose easier configuration of this value in https://github.com/mergestat/helm-charts

**Comment by amenowanna** [comment]
Prioritizing this ahead of #331 since we think this will mitigate a majority of the issues we have seen in the wild.

**Comment by patrickdevivo** [comment]
@amenowanna should we close this based on the change in: https://github.com/mergestat/helm-charts/pull/88

or want to validate this further?

**Comment by amenowanna** [comment]
This only applies to init containers right? Do we need to add it to other paths?

**Comment by amenowanna** [comment]
Discussed this on a call and right now this is sufficient.
