### ISSUE TITLE
Username in Connect page should reflect current user

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#612]
The username that is being displayed in our Connect page should show the current user. Currently it seems to be hardcoded. 

![Image](https://user-images.githubusercontent.com/10135546/205322768-73383ea6-59e3-4ccf-a616-777519a840e7.png)

**Comment by german-mergestat** [comment]
@patrickdevivo @amenowanna user comes from `databaseConnection` function. Should I show user coming from `currentMergeStatUser` function instead?

![connection](https://user-images.githubusercontent.com/109089565/208526813-b69d507f-a317-414b-92e8-64e3db19d4ae.png)

**Comment by amenowanna** [comment]
Yes, it should be the same value that we show on the upper right-hand side of the UI to show what user is logged in.
