### ISSUE TITLE
When selecting "Sync Now" in the console we need to insert type_group to respect concurrency

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#633]
In the console when we select `Sync Now` we are not setting the type_group value in mergestat.repo_sync_queue. The default for this column is `DEFAULT` and the concurrency for `GITHUB` is then no longer used and we hit the secondary rate limit. We need to add the correct type when we perform this action.

**Comment by patrickdevivo** [comment]
I wonder if this should be done via a postgres function (exposed as a mutation in the graphql schema), something like `mergestat.sync_now(repoSyncID, ...)` to encapsulate this business logic on the backend to make it easier to change/adjust in the future.

We'd still need to update the frontend to call the function instead.

**Comment by patrickdevivo** [comment]
Question for @german-mergestat does this also add this behavior to the _other_ "Sync Now" button?

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/57259/208264032-e8a32eb6-8485-44ce-a302-affd567a1473.png">

Just want to make sure - if it doesn't do you mind creating another ticket to track that - thanks!
