### ISSUE TITLE
Add better support for Bitbucket repositories

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#634]
Bring Bitbucket support up to the level we currently support GitHub repos:

- [ ] Bitbucket authentication (token based)
- [ ] Repo auto imports that support Bitbucket orgs/users
- [ ] The console should reflect Bitbucket repos (indicate with icons, parse out org images, etc)
- [ ] Base set of Bitbucket API syncs

**Comment by amenowanna** [comment]
Closing this in favor of tracking the feature in [Notion](https://www.notion.so/mergestat/45573b0fff2f468da416a4679d183ae9?v=eafa267909ce4ef7b18e7448ac360941&p=556c3f44533842988c5d6c0f9598d3c0&pm=s)
