### ISSUE TITLE
Odd behavior when adding multiple repos at once - either with the direct URL or CSV insert

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#692]
To reproduce, try adding multiple repos either via direct URL or CSV

![Image](https://user-images.githubusercontent.com/57259/209380285-9be9dfd5-8f68-41a9-8ded-f28681bb39dd.png)

**Comment by ramiroJCB** [comment]
this is was comes form the logs after tryin to replicate this

![Image](https://user-images.githubusercontent.com/43893061/220175922-082d14a3-b62e-4bdc-8b56-071ca06c2569.png)
