### ISSUE TITLE
Unable to sync PR Commits

### ISSUE THREAD

**Issue by kapilkumawat86** [mergestat/mergestat#702]
Getting this error
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/57665511/211047382-1acbac21-fdf7-4f13-9edf-be7b1c490e90.png">

Need help

**Comment by patrickdevivo** [comment]
Hi @kapilkumawat86 - could you try removing the `.git` from the repo name and see if that helps?

If so, we should probably be smarter about parsing/handing the `.git` if it's there in a repo name

**Comment by kapilkumawat86** [comment]
Thanks @patrickdevivo for quick help and this worked...
