### ISSUE TITLE
Bot Handle  in issues and reactivity.

### ISSUE THREAD

**Issue by gedw99** [mergestat/mergestat#752]
I am a newbie to this project 

I saw that there are metrics for issues . Just saw the example 

https://docs.mergestat.com/mergestat/use-cases/engineering-transparency/

And issues leads to:

https://github.com/mergestat/mergestat/tree/main/examples/github/issues

My use case is knowing when a bot handle was put into an issue, who did it and what it’s args were.

for example a bot handle that automates some CI or CD task. 

Also it would be fab is you ended up having a feed on any sql query result changing , so that  as soon as that bot handle input is put in by a user other systems can react to it via a web hook.

Having the graphana metric on the bot handle  aspects is also needed.

Thanks in advance

**Comment by patrickdevivo** [comment]
hi @gedw99 just to clarify - do you mean identifying whether an issue was created by a bot? I will check in the GitHub API and see if they have a field for tracking that. I know bots often comment/open issues with a handle that has the string `[bot]`  in it, which could be identified in SQL using a string match or regular expression. We could put together some examples around that

**Comment by gedw99** [comment]
Hey @patrickdevivo 

sounds hopeful regarding string search of the contents of an issue. That’s what I was hoping was possible too.

I also would like to know what you suggest. Was an issue created by a bot.

Also I want to know when a human put a bot command handle into an issue comment. 

Does that make it clearer ?

The intent is to be able to know:

1. when, who and the args of the bot that a human wrote into an issue. 

Would be bonus if I was able to subscribe to a query from the cli or some daemon so that I get  new events of this type. I don’t know if your architect supports this conceptually btw. I call them “Squeries”. Under the hood it could be a graphql subscription or a CDC running under postresql. I expect your architecture is a bit of a CQRS style setup and so the Squery would be possible to do using SQL.

sorry to ram so much into a single issue but I am hoping that it’s also welcome in terms of product extensibility.

**Comment by amenowanna** [comment]
@gedw99 I apologize for the lack of response here. So far we have not built in the ability to do monitoring and notifications through our app. That being said we have had a lot of success doing that with Grafana. If you are still interested in this and would like some help let us know and we would be happy to explore this with you. Closing this for now but we can keep chatting here or through other means.
