### ISSUE TITLE
Ensure GitHub repo auto imports respect the concurrency requirements of the GitHub API (one request at a time)

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#791]
One outcome of switching the repo auto importer to use the v3 GitHub API (https://github.com/mergestat/mergestat/issues/540) instead of the v4 API _through mergestat-lite_ is that we no longer respect the global rate limiter implementation our use of `mergestat-lite` allowed.

Now that we're using `sqlq`, we should consider pushing this concurrency constraint into the queuing mechanism, and have it in place for _all_ places that use the GitHub API, as a potential solution.

However, it could be that enforcing _this_ concurrency at the sqlq level may not make sense, as our work on custom repo syncers evolves. We may need a way to plug into this rate limiter at the custom repo syncer implementation, for syncers that make use of the GitHub API.

**Comment by ramiroJCB** [comment]
Currently blocked because of a  recently discovered zombie thread when imports fails or sometimes it success.We would need a new digest of sqlq into this branch to address this issue
