### ISSUE TITLE
Add `_mergestat_synced_at` column to `GRYPE_REPO_SCAN` syncer

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#793]
Missed this in the initial implementation: https://github.com/mergestat/mergestat/blob/main/migrations/900000000000023_grype_repo_scan.up.sql#L5, we want to include the `_mergestat_synced_at` column.

Should be addressable in a single migration.

**Comment by amenowanna** [comment]
We should also add the comments to the table and columns
