### ISSUE TITLE
Odd/incorrect behavior when query returns 0 rows of data

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#824]
Seeing some odd behavior when a SQL execution returns no rows of data. For some reason I'm consistently seeing `63 rows impacted` when there are no rows returned. I think we may need to take a look at this logic again/

<img width="2047" alt="image" src="https://user-images.githubusercontent.com/57259/218275674-033e460c-8aa7-4570-a539-e3aee6bb4c8e.png">

**Comment by ramiroJCB** [comment]
@patrickdevivo  is there a way to replicate this?
I keep trying and I cannot. maybe solved ?

**Comment by patrickdevivo** [comment]
Here's another example I was able to trigger @ramiroJCB 

<img width="2046" alt="image" src="https://user-images.githubusercontent.com/57259/220181139-1048d3d3-d4bd-4492-94ad-43e78aae62c9.png">
