### ISSUE TITLE
Saved queries should also persist visualizations

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#829]
When a user saves a query (and gives it a name/description) they should also be able to save any associated data visualizations with it. In order to do this, we'll need to be able to serialize the data viz configurations into JSON and store in the DB along with the SQL/name/description.

**Comment by amenowanna** [comment]
We have a jsonb `metadata` column in our `mergestat.saved_queries` column that we intend to use to store this in


![Image](https://user-images.githubusercontent.com/10135546/228347894-5365854e-a019-4548-8fc4-f38b735345a8.png)
