### ISSUE TITLE
Add support for migration command to worker

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#844]
We currently are not able to deploy the latest version of MergeStat to Kubernetes because we have a new dependency between the `mergestat` and `sqlq` schemas we introduced in this [migration](https://github.com/mergestat/mergestat/blob/main/migrations/900000000000031_sqlq_support_schema.up.sql)

In k8s we run an [initContainer](https://github.com/mergestat/helm-charts/blob/ccab2cb7640e6b6b3771032eb26d497164d5e33b/charts/fuse/templates/worker/deployment.yaml#L30) as part of our deployment for the worker and it currently only runs the migrations for the `mergestat` schema. So, when it runs it currently breaks on deployments that previously did not have the `sqlq' schema added.

To address this we would like to introduce a command we can call from the worker `cmd/migrate` that will run both the `sqlq` and `mergestat` schema migrations.

**Comment by patrickdevivo** [comment]
Closing this out as we resolved by simply removing the init container: https://github.com/mergestat/helm-charts/pull/109 and are now only running migrations as part of the `worker` startup
