### ISSUE TITLE
Add support for syncing GitHub repo security settings

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#846]
we'll need to find where in the API this is:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-security-and-analysis-settings-for-your-repository

**Comment by amenowanna** [comment]
@patrickdevivo I think when we discussed this with Peter we found it [here](https://github.blog/changelog/2022-12-20-code-security-enablement-settings-on-the-list-organization-repositories-rest-api/) which links to these [api docs](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories).

**Comment by patrickdevivo** [comment]
Just did some research, unfortunately it doesn't appear that this is available in the GraphQL API - which is how we're retrieving data for our `GITHUB_REPO_METADATA` sync (via `mergestat-lite`). This means, if we wanted to add this data to the `github_repo_info` table, we'd likely need to re-implement that whole syncer to use the GitHub v3 REST API. Which isn't _too bad_, but I was hoping we could just add it to our existing pattern - which unfortunately seems not possible from what I've found.
