### ISSUE TITLE
can't loading libgit2.so

### ISSUE THREAD

**Issue by jingkai1** [mergestat/mergestat#85]
askgit: error while loading shared libraries: libgit2.so.1.1

**Comment by jingkai1** [comment]
askgit -v
askgit: error while loading shared libraries: libgit2.so.1.1: cannot open shared object file: No such file or directory

whereis libgit2.so.1.1
libgit2.so.1: /usr/local/lib/libgit2.so.1.1

**Comment by patrickdevivo** [comment]
closing due to staleness, please let me know if you've encountered this again in recent releases. sorry I wasn't able to follow up a year ago!
