### ISSUE TITLE
Git Remotes sync not working when using file url for repo path

### ISSUE THREAD

**Issue by amenowanna** [mergestat/mergestat#868]
If we add a local repo with `file://` the git remotes sync does not work. If we don't prefix with `file://` then the sync will run. It also appears that our git syncs work just fine this way but we need to check all the syncers if we change the pattern here for adding local repos.

**Comment by riyaz-ali** [comment]
This is the [default behaviour of `git`](https://git-scm.com/docs/git-clone#_git_urls) when cloning _local repositories_.

> For local repositories, also supported by Git natively, the following syntaxes may be used:
> 
> - `/path/to/repo.git/`
> - `file:///path/to/repo.git/`
> 
> These two syntaxes are mostly equivalent, except the former implies `--local` option.

The [`--local,-l`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---local) flag _" bypasses the normal 'Git-aware' transport mechanism and clones the repository by making a copy of HEAD and everything under objects and refs directories"_.

Unfortunately, the `go-git` library doesn't support specifying `--local,-l` option when cloning. But it does state that _"it shells out to native `git` when cloning local paths"_ <sup>[[source]](https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md)</sup> which means that using absolute path we can imply `--local,-l` and get the desired behaviour.

So, as a solution, if someone wants to use the git remotes sync with a local repository, they MUST use the absolute path (w/o `file://` uri scheme)

**Comment by riyaz-ali** [comment]
Added as a recommendation in the linked PR
