### ISSUE TITLE
Add alert banner to query UI when results exceed limit

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#924]
In the `Queries` UI, if a query has results more than the limit (currently 1000 rows), we should show a banner that says `Result set exceeds the limits of the UI. Please use another SQL client to access more rows`

**Comment by patrickdevivo** [comment]
@emilyvandewalle when you have a chance, could you take a look to see if we still have an example this in Figma?

**Comment by emilyvandewalle** [comment]
I was thinking about using a similar warning pattern here like the `Read-only` warning to save space

![image](https://user-images.githubusercontent.com/36261498/225342216-157d5c24-9321-4029-9353-f28b854c2563.png)


See designs [here](https://www.figma.com/file/cP3iH1A6BjtUtyAPeqrPPB/MergeStat-%E2%80%93-Saved-queries?node-id=325%3A4043&t=CnvgC1FhJl7bqryF-1)
