### ISSUE TITLE
Last sync is not being recorded when sync failed (with Time Out error)

### ISSUE THREAD

**Issue by german-mergestat** [mergestat/mergestat#943]
Last sync is not being recorded in `repo_syncs` table when it is a `Failed` sync. This affects repo stats.

The scenario was follow:

- Repo `mergestat/mergestat` was imported manually .
- `Git Blame` was synced manually (No scheduled). It field and the last sync was not recorded. Maybe because the error was a `TimeOut`.

![repo-syncs](https://user-images.githubusercontent.com/109089565/225762447-6f409e5b-52f6-4df1-9370-d10c77cb98ed.png)

- We can see in repo_syncs table, the `last_completed_repo_sync_queue_id` column was not recored for `GIT_BLAME` dispite it had an executed sync

![Screenshot 2023-03-16 at 5 19 06 PM](https://user-images.githubusercontent.com/109089565/225765429-7af0a9de-4dcc-46d8-a36d-9451d08594b1.png)

it should be recored the `repo_sync_queue` with the id `130`.

![repo-sync-queue](https://user-images.githubusercontent.com/109089565/225763797-831107d9-1a43-4c3d-a93c-95a86d517dbc.png)

its sync logs are

![syncs-logs](https://user-images.githubusercontent.com/109089565/225764787-164f2a6a-c65e-47f9-ab66-d20c84dc6b9d.png)

- Finally it affects the repo stats due it does not count that sync in the error column.

![repo-stat](https://user-images.githubusercontent.com/109089565/225764381-a272c4d3-e252-4fe5-937b-75edf7ea1f3b.png)

**Comment by amenowanna** [comment]
Closing this as we are now using sqlq and have created a new experience
