### ISSUE TITLE
Let's *not* clone repos by default when executing container-based syncs

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#967]
- Let’s address this, it’s important for preventing unnecessary clones of *****large***** repos when all we need is data out of an API
- Let’s remove the pre-run clone step and move clones into the syncs for syncs that need it

@riyaz-ali - @amenowanna and I discussed this today and decided we want to address this now. Basically for large repos it adds a lot of overhead for syncs that don't require the contents of the repo. Or even for "normal" sized repos but for a deployment that has lots of them, it adds quite a bit of overhead in aggregate.

This would push the clone behavior into the sync implementation, which I think is good for the sync implementation to "own" anyways. Some syncs might be able to do a shallow clone for example, or a partial clone. It allows us to be more efficient/selective with the data we work with.

**Comment by patrickdevivo** [comment]
Should we clone or should we not?
- Can we look at metadata on the container image to determine this? Use the `LABEL` instruction

**Comment by riyaz-ali** [comment]
Added support with #982 👍

**Comment by riyaz-ali** [comment]
To test, publish an image with a [docker `LABEL`](https://docs.docker.com/engine/reference/builder/#label) in the `Dockerfile` called `com.mergestat.sync.clone` set to `never` (to skip cloning).

I've tested with `mergestat/sync-github-pull-request@sha256: 4fde5001d2a299dfc8b2e69a6a5dc4a9234022046b736f3fbeced5b0f2346617` which has the label set to `never`. (The sync fails becuase `gh` cli expects a git repository to parse the remote; needs refactoring @patrickdevivo )
