### ISSUE TITLE
Address queue concurrency for container-based syncs

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#968]
- Since we are using the same queue right now we can’t take advantage of how we manage concurrency for things that are not rate limited. For now let’s control that for users and have a default (unbound) and a github (concurrency of 1) queue
    - When we ***add*** a `container_syncs` we should look up what the queue should be based either on a hardcoded mapping (in the frontend?) or a pattern match (any sync name with `*-github-*` in it?)

**Comment by amenowanna** [comment]
This was addressed in another issue/pr
